openapi: 3.0.3
info:
  title: 홀로그래픽 카드 커뮤니티 API
  description: 홀로그래픽 카드 커뮤니티 프로젝트의 백엔드 API 스펙
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8090/api
    description: 개발 서버
  - url: https://api.example.com
    description: 프로덕션 서버

security:
  - bearerAuth: []

paths:
  # 인증 관련 API
  /collections/users/auth-with-password:
    post:
      tags:
        - Authentication
      summary: 사용자 로그인
      description: 이메일과 비밀번호로 로그인
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - identity
                - password
              properties:
                identity:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 6
                  example: password123
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  record:
                    $ref: '#/components/schemas/User'
        '400':
          description: 잘못된 요청
        '401':
          description: 인증 실패

  /collections/users:
    post:
      tags:
        - Authentication
      summary: 사용자 등록
      description: 새 사용자 계정 생성
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - passwordConfirm
                - name
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  minLength: 6
                  example: password123
                passwordConfirm:
                  type: string
                  minLength: 6
                  example: password123
                name:
                  type: string
                  example: John Doe
      responses:
        '200':
          description: 등록 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: 잘못된 요청

  # 카드 관련 API
  /collections/unified_cards/records:
    get:
      tags:
        - Cards
      summary: 통합 카드 목록 조회
      description: 통합 카드 목록을 페이지네이션과 함께 조회
      parameters:
        - name: page
          in: query
          description: 페이지 번호
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: perPage
          in: query
          description: 페이지당 항목 수
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 30
        - name: sort
          in: query
          description: 정렬 필드
          schema:
            type: string
            example: "-created"
        - name: filter
          in: query
          description: 필터 조건
          schema:
            type: string
            example: "context = 'community'"
        - name: expand
          in: query
          description: 관련 데이터 확장
          schema:
            type: string
            example: "community_creator"
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                  perPage:
                    type: integer
                  totalItems:
                    type: integer
                  totalPages:
                    type: integer
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/UnifiedCard'

    post:
      tags:
        - Cards
      summary: 통합 카드 생성
      description: 새로운 통합 카드 생성
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnifiedCardInput'
      responses:
        '200':
          description: 생성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnifiedCard'
        '400':
          description: 잘못된 요청
        '401':
          description: 인증 필요

  /collections/unified_cards/records/{id}:
    get:
      tags:
        - Cards
      summary: 통합 카드 상세 조회
      description: 특정 통합 카드의 상세 정보 조회
      parameters:
        - name: id
          in: path
          required: true
          description: 카드 ID
          schema:
            type: string
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnifiedCard'
        '404':
          description: 카드를 찾을 수 없음

    patch:
      tags:
        - Cards
      summary: 통합 카드 수정
      description: 기존 통합 카드 정보 수정
      parameters:
        - name: id
          in: path
          required: true
          description: 카드 ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnifiedCardUpdate'
      responses:
        '200':
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnifiedCard'
        '400':
          description: 잘못된 요청
        '401':
          description: 인증 필요
        '403':
          description: 권한 없음
        '404':
          description: 카드를 찾을 수 없음

    delete:
      tags:
        - Cards
      summary: 통합 카드 삭제
      description: 통합 카드 삭제
      parameters:
        - name: id
          in: path
          required: true
          description: 카드 ID
          schema:
            type: string
      responses:
        '204':
          description: 삭제 성공
        '401':
          description: 인증 필요
        '403':
          description: 권한 없음
        '404':
          description: 카드를 찾을 수 없음

  # 템플릿 관련 API
  /templates/search:
    get:
      tags:
        - Templates
      summary: 템플릿 검색
      description: 템플릿을 검색하고 필터링
      parameters:
        - name: q
          in: query
          description: 검색어
          schema:
            type: string
        - name: category
          in: query
          description: 카테고리
          schema:
            type: string
        - name: minPrice
          in: query
          description: 최소 가격
          schema:
            type: number
        - name: maxPrice
          in: query
          description: 최대 가격
          schema:
            type: number
        - name: sort
          in: query
          description: 정렬
          schema:
            type: string
            enum: [price, rating, downloads, created]
        - name: page
          in: query
          description: 페이지 번호
          schema:
            type: integer
            default: 1
        - name: perPage
          in: query
          description: 페이지당 항목 수
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  templates:
                    type: array
                    items:
                      $ref: '#/components/schemas/Template'
                  total:
                    type: integer
                  page:
                    type: integer
                  perPage:
                    type: integer

  /templates/trending:
    get:
      tags:
        - Templates
      summary: 인기 템플릿 조회
      description: 현재 인기 있는 템플릿 목록 조회
      parameters:
        - name: limit
          in: query
          description: 조회할 템플릿 수
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Template'

  /templates/recommended:
    get:
      tags:
        - Templates
      summary: 추천 템플릿 조회
      description: 사용자에게 추천하는 템플릿 목록 조회
      responses:
        '200':
          description: 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Template'

  # 파일 업로드 API
  /files/{collection}/{recordId}/{field}:
    post:
      tags:
        - Files
      summary: 파일 업로드
      description: 특정 컬렉션의 레코드에 파일 업로드
      parameters:
        - name: collection
          in: path
          required: true
          description: 컬렉션 이름
          schema:
            type: string
        - name: recordId
          in: path
          required: true
          description: 레코드 ID
          schema:
            type: string
        - name: field
          in: path
          required: true
          description: 필드 이름
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: 업로드 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  collectionId:
                    type: string
                  collectionName:
                    type: string
                  recordId:
                    type: string
                  filename:
                    type: string
                  url:
                    type: string
        '400':
          description: 잘못된 요청
        '401':
          description: 인증 필요

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "user_id_123"
        email:
          type: string
          format: email
          example: "user@example.com"
        name:
          type: string
          example: "John Doe"
        avatar:
          type: string
          example: "https://example.com/avatar.jpg"
        emailVisibility:
          type: boolean
          default: false
        verified:
          type: boolean
          default: false
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time

    UnifiedCard:
      type: object
      properties:
        id:
          type: string
          example: "card_id_123"
        title:
          type: string
          example: "Amazing Holographic Card"
        description:
          type: string
          example: "A beautiful holographic card with special effects"
        holographic_image:
          type: string
          example: "https://example.com/holographic.jpg"
        holographic_back_image:
          type: string
          example: "https://example.com/holographic_back.jpg"
        holographic_effect:
          type: string
          enum: [overlay, soft-light, hard-light]
          example: "overlay"
        holographic_intensity:
          type: number
          minimum: 0
          maximum: 100
          example: 75
        holographic_animation_duration:
          type: number
          minimum: 100
          maximum: 2000
          example: 1000
        photocard_rarity:
          type: string
          enum: [common, rare, epic, legendary]
          example: "rare"
        photocard_season:
          type: string
          example: "2024 Spring"
        photocard_total_views:
          type: number
          example: 1500
        photocard_unique_collectors:
          type: number
          example: 250
        photocard_completion_rate:
          type: number
          minimum: 0
          maximum: 100
          example: 85
        photocard_collections:
          type: array
          items:
            type: object
        community_creator:
          type: string
          example: "user_id_123"
        community_is_public:
          type: boolean
          example: true
        community_tags:
          type: array
          items:
            type: string
          example: ["kbo", "baseball", "holographic"]
        community_likes:
          type: number
          example: 42
        community_downloads:
          type: number
          example: 15
        community_rating:
          type: number
          minimum: 0
          maximum: 5
          example: 4.5
        community_rating_count:
          type: number
          example: 20
        context:
          type: string
          enum: [test, main, gallery, community]
          example: "community"
        migrated_from:
          type: string
          enum: [phase1, phase2, phase4, unified]
          example: "unified"
        legacy_id:
          type: string
          example: "legacy_card_123"
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time

    UnifiedCardInput:
      type: object
      required:
        - title
        - holographic_image
        - holographic_effect
        - holographic_intensity
        - community_creator
        - community_is_public
        - context
      properties:
        title:
          type: string
          example: "Amazing Holographic Card"
        description:
          type: string
          example: "A beautiful holographic card"
        holographic_image:
          type: string
          example: "https://example.com/holographic.jpg"
        holographic_back_image:
          type: string
          example: "https://example.com/holographic_back.jpg"
        holographic_effect:
          type: string
          enum: [overlay, soft-light, hard-light]
          example: "overlay"
        holographic_intensity:
          type: number
          minimum: 0
          maximum: 100
          example: 75
        holographic_animation_duration:
          type: number
          minimum: 100
          maximum: 2000
          example: 1000
        photocard_rarity:
          type: string
          enum: [common, rare, epic, legendary]
          example: "rare"
        photocard_season:
          type: string
          example: "2024 Spring"
        community_creator:
          type: string
          example: "user_id_123"
        community_is_public:
          type: boolean
          example: true
        community_tags:
          type: array
          items:
            type: string
          example: ["kbo", "baseball"]
        community_likes:
          type: number
          default: 0
        community_downloads:
          type: number
          default: 0
        community_rating:
          type: number
          default: 0
        community_rating_count:
          type: number
          default: 0
        context:
          type: string
          enum: [test, main, gallery, community]
          example: "community"

    UnifiedCardUpdate:
      type: object
      properties:
        title:
          type: string
          example: "Updated Card Title"
        description:
          type: string
          example: "Updated description"
        holographic_intensity:
          type: number
          minimum: 0
          maximum: 100
          example: 80
        community_is_public:
          type: boolean
          example: false
        community_tags:
          type: array
          items:
            type: string
          example: ["updated", "tags"]
        community_likes:
          type: number
          example: 50

    Template:
      type: object
      properties:
        id:
          type: string
          example: "template_id_123"
        name:
          type: string
          example: "KBO Team Template"
        description:
          type: string
          example: "A template for KBO team cards"
        category:
          type: string
          example: "sports"
        price:
          type: number
          example: 9.99
        creator:
          type: string
          example: "user_id_123"
        rating:
          type: number
          minimum: 0
          maximum: 5
          example: 4.5
        rating_count:
          type: number
          example: 25
        downloads:
          type: number
          example: 150
        is_public:
          type: boolean
          example: true
        template_data:
          type: object
        preview_image:
          type: string
          example: "https://example.com/preview.jpg"
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: "Validation failed"
        data:
          type: object
          additionalProperties: true
