# Social API Contract
# Feature: 004-production-service-integration
# Requirements: FR-016 to FR-020

openapi: 3.0.3
info:
  title: Social API
  version: 1.0.0
  description: 커뮤니티 소셜 기능 API (좋아요, 댓글, 알림)

servers:
  - url: /api
    description: Social interaction endpoints

paths:
  /cards/{cardId}/likes:
    get:
      summary: 좋아요 목록
      description: 카드의 좋아요 목록 조회
      operationId: getCardLikes
      tags:
        - Likes
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: perPage
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 좋아요 목록
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikeListResponse'

    post:
      summary: 좋아요 추가
      description: 카드에 좋아요 (FR-017)
      operationId: likeCard
      tags:
        - Likes
      security:
        - cookieAuth: []
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: 좋아요 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Like'
        '409':
          description: 이미 좋아요함
        '401':
          description: 인증 필요

    delete:
      summary: 좋아요 취소
      description: 카드 좋아요 취소 (FR-017)
      operationId: unlikeCard
      tags:
        - Likes
      security:
        - cookieAuth: []
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 좋아요 취소 성공
        '404':
          description: 좋아요 없음

  /cards/{cardId}/liked:
    get:
      summary: 좋아요 여부 확인
      description: 현재 사용자가 좋아요 했는지 확인
      operationId: checkLiked
      tags:
        - Likes
      security:
        - cookieAuth: []
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 좋아요 상태
          content:
            application/json:
              schema:
                type: object
                properties:
                  liked:
                    type: boolean

  /cards/{cardId}/comments:
    get:
      summary: 댓글 목록
      description: 카드의 댓글 목록 조회
      operationId: getCardComments
      tags:
        - Comments
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: perPage
          in: query
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          schema:
            type: string
            enum: [created, likes]
            default: created
      responses:
        '200':
          description: 댓글 목록
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentListResponse'

    post:
      summary: 댓글 작성
      description: 카드에 댓글 작성 (FR-018)
      operationId: createComment
      tags:
        - Comments
      security:
        - cookieAuth: []
      parameters:
        - name: cardId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCommentRequest'
      responses:
        '201':
          description: 댓글 작성 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '400':
          description: 유효성 검사 실패
        '401':
          description: 인증 필요

  /comments/{id}:
    patch:
      summary: 댓글 수정
      operationId: updateComment
      tags:
        - Comments
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCommentRequest'
      responses:
        '200':
          description: 수정 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '403':
          description: 권한 없음

    delete:
      summary: 댓글 삭제
      operationId: deleteComment
      tags:
        - Comments
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 삭제 성공
        '403':
          description: 권한 없음

  /notifications:
    get:
      summary: 알림 목록
      description: 사용자 알림 목록 조회 (FR-020)
      operationId: getNotifications
      tags:
        - Notifications
      security:
        - cookieAuth: []
      parameters:
        - name: unread
          in: query
          schema:
            type: boolean
          description: 읽지 않은 알림만
        - name: type
          in: query
          schema:
            type: string
            enum: [like, comment, follow, gacha, system]
          description: 알림 유형 필터
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: perPage
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: 알림 목록
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationListResponse'

  /notifications/unread-count:
    get:
      summary: 읽지 않은 알림 수
      operationId: getUnreadCount
      tags:
        - Notifications
      security:
        - cookieAuth: []
      responses:
        '200':
          description: 읽지 않은 알림 수
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer

  /notifications/{id}/read:
    post:
      summary: 알림 읽음 처리
      operationId: markAsRead
      tags:
        - Notifications
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 읽음 처리 성공

  /notifications/read-all:
    post:
      summary: 모든 알림 읽음 처리
      operationId: markAllAsRead
      tags:
        - Notifications
      security:
        - cookieAuth: []
      responses:
        '200':
          description: 모든 알림 읽음 처리 성공

  /notifications/subscribe:
    get:
      summary: 실시간 알림 구독
      description: WebSocket 연결로 실시간 알림 수신 (FR-019)
      operationId: subscribeNotifications
      tags:
        - Notifications
      security:
        - cookieAuth: []
      responses:
        '101':
          description: WebSocket 업그레이드

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: pb_auth

  schemas:
    Like:
      type: object
      properties:
        id:
          type: string
        user:
          type: string
        card:
          type: string
        created:
          type: string
          format: date-time
        expand:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/User'

    LikeListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Like'
        page:
          type: integer
        perPage:
          type: integer
        totalItems:
          type: integer

    Comment:
      type: object
      properties:
        id:
          type: string
        user:
          type: string
        card:
          type: string
        content:
          type: string
        created:
          type: string
          format: date-time
        updated:
          type: string
          format: date-time
        expand:
          type: object
          properties:
            user:
              $ref: '#/components/schemas/User'

    CommentListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
        page:
          type: integer
        perPage:
          type: integer
        totalItems:
          type: integer

    CreateCommentRequest:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          minLength: 1
          maxLength: 500
          description: 댓글 내용

    UpdateCommentRequest:
      type: object
      properties:
        content:
          type: string
          minLength: 1
          maxLength: 500

    Notification:
      type: object
      properties:
        id:
          type: string
        user:
          type: string
        type:
          type: string
          enum: [like, comment, follow, gacha, system]
        data:
          type: object
          description: 알림 유형별 데이터
        is_read:
          type: boolean
        created:
          type: string
          format: date-time

    NotificationListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Notification'
        page:
          type: integer
        perPage:
          type: integer
        totalItems:
          type: integer
        unreadCount:
          type: integer

    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        avatar:
          type: string

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
